branch-defaults:
  default:
    environment: testenvo
  master:
    environment: testenvo
global:
  application_name: Testenvo
  default_ec2_keyname: Testkey
  default_platform: 64bit Amazon Linux 2016.03 v2.1.2 running PHP 5.6
  default_region: eu-central-1
  profile: eb-cli
  sc: git
